###
GET http://localhost:3000/post

###
GET http://localhost:3000/post?sender=abcd

###
GET http://localhost:3000/post/69567f030f33c0ed9c5bf1cc

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "abcd",
    "imageUrl": "image3.jpg",
    "description": "description of a post",
    "date": "2026-01-01T13:31:41.786Z"
}

###
PUT http://localhost:3000/post/69567f030f33c0ed9c5bf1cc
Content-Type: application/json

{
    "imageUrl": "newimage4.jpg",
    "description": "the new descriptio of a post",
    "date": "2026-01-01T13:57:10.573Z"
}

###
DELETE  http://localhost:3000/post/695677ab9627eb9bf2816a6b

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/69591ea638aebd4600b7ed11

###
GET http://localhost:3000/comment?postId=69591889a973fc146336e4

###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "sender": "abcd",
    "postId": "69591889a973fc146336e4",
    "content": "this post is great",
    "date": "2026-01-01T13:31:41.786Z"

}

###
PUT http://localhost:3000/comment/69591d385d809d137e9865ba
Content-Type: application/json

{
    "postId": "69591d385d809d137e9865ba",
    "content": "this post is okay",
    "date": "2026-01-01T13:31:41.786Z"
}

###
DELETE  http://localhost:3000/comment/69591d385d809d137e9865ba
