###
GET http://localhost:3000/post

###
GET http://localhost:3000/post?sender=abcd

###
GET http://localhost:3000/post/6977ae776368538c84d6a40c

###
POST http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E
Content-Type: application/json

{
    "sender": "abcd",
    "imageUrl": "image3.jpg",
    "description": "ssdescription of a post",
    "date": "2026-01-01T13:31:41.786Z"
}

###
PUT http://localhost:3000/post/6977ad2ab92634f6829f261c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E
Content-Type: application/json

{
    "imageUrl": "newimage4.jpg",
    "description": "the new descriptio of a post",
    "date": "2026-01-01T13:57:10.573Z"
}

###
DELETE  http://localhost:3000/post/6977ad2ab92634f6829f261c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTAyMzQsImV4cCI6MTc2OTQ1MzgzNH0.yity4uYc1cd5l7rkIkjy48QK9wJ0cicD6lDP4PowplQ

###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/6977aede6368538c84d6a416

###
GET http://localhost:3000/comment?postId=69591889a973fc146336e4

###
POST http://localhost:3000/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTAyMzQsImV4cCI6MTc2OTQ1MzgzNH0.yity4uYc1cd5l7rkIkjy48QK9wJ0cicD6lDP4PowplQ
Content-Type: application/json

{
    "sender": "abcd",
    "postId": "69591889a973fc146336e4",
    "content": "this post is great",
    "date": "2026-01-01T13:31:41.786Z"

}

###
PUT http://localhost:3000/comment/6977aede6368538c84d6a416
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTAyMzQsImV4cCI6MTc2OTQ1MzgzNH0.yity4uYc1cd5l7rkIkjy48QK9wJ0cicD6lDP4PowplQ
Content-Type: application/json

{
    "postId": "69591889a973fc146336e4",
    "content": "this post is okay",
    "date": "2026-01-01T13:31:41.786Z"
}

###
DELETE  http://localhost:3000/comment/69591d385d809d137e9865ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user?username=abc

###
GET http://localhost:3000/user/69736c31af386f4f1e90c6a8

###
POST http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E
Content-Type: application/json

{
    "username": "abcsd",
    "email": "emaiss@gmail.com",
    "password": "123",
    "profilePicture": "usrimg.jpg"
}

###
PUT http://localhost:3000/user/6977b00e6368538c84d6a426
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E
Content-Type: application/json

{
    "username": "abca",
    "profilePicture": "newpic.jpg"
}

###
DELETE  http://localhost:3000/user/6977b00e6368538c84d6a426
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTc0ZDJkNDJlNDA2OWU4ZGUyYjZiOTIiLCJpYXQiOjE3Njk0NTA2NzYsImV4cCI6MTc2OTQ1NDI3Nn0.OE8JLWLwJqvytwLIO-yj_SPxL2zRZjeE5CaVtVqki3E

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "abcyari",
    "email": "emaillyarn@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "emaillyarin@gmail.com",
    "password": "123"
}